name: Cron Update PHP Modules
on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  update-composer-modules:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    runs-on: ubuntu-latest
    name: Update PHP Modules
    strategy:
      fail-fast: false
      matrix:
        BRANCH:
          - develop
          - 8.0.x
          - 1.7.8.x
    env:
      GH_BRANCH: ${{ matrix.BRANCH }}

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv, simplexml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ env.GH_BRANCH }}

      - name: Install Composer dependencies
        run: |
          composer self-update --2.2
          composer install --prefer-dist

      - name: Execute script for updating modules
        run: php .github/workflows/cron_update_modules/script.php ${{ env.GH_BRANCH }}
        
      - name: Cache modules
        uses: actions/cache@v2
        id: cache-modules
        env:
          cache-name: cache-modules
        with:
          path: cron_php_update_modules.txt
          key: ${{ env.GH_BRANCH }}-${{ env.cache-name }}

      - name: Create Pull Request
        run: echo ${{ steps.cache-modules.outputs }}
